[tool.poetry]
name = "toolbag"
version = "0.1.0"
description = ""
authors = ["Ted Fulk <tfulk@getspiffy.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
tedfulk-kb-pycrawler = "^0.1.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
